py/world: strict booleans instead of ints
SWIG seems strict enough to reject ints when a bool is expected

For example:

  File "/path/kiki//py/world.py", line 177, in create
    exit_gate = KikiGate (entry["active"])
  File "/path/kiki/py/kiki.py", line 1911, in __init__
    this = _kiki.new_KikiGate(open)
NotImplementedError: Wrong number or type of arguments for overloaded
function 'new_KikiGate'.
  Possible C/C++ prototypes are:
    KikiGate::KikiGate(bool)
    KikiGate::KikiGate()