SWIG: remove const ref as generated code seems buggy
Due to this const ref, the result wouldn't compile properly

../src/../SWIG/KikiPy_wrap.cpp: In function 'PyObject*
_wrap_KikiText_getText(PyObject*, PyObject*)':
../src/../SWIG/KikiPy_wrap.cpp:13436:63: error: taking address of rvalue
[-fpermissive]
13436 |   result = (std::string *) &((KikiText const *)arg1)->getText();
      |                                                               ^